name: Terraform CI Pipeline

on:
  push:
    branches:
      - master

  workflow_dispatch:

jobs:
  my_job:
    name: Deploy to staging CI
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run a one-line script
        run: echo Hello, world!

      - name: Terraform Init Validate and Plan
        run: |
          terraform init
          terraform validate
          terraform plan
