name: "Terraform Azure Deploy"

on:
  pull_request:
    branches:
      - main


permissions:
  id-token: write
  contents: read

jobs:
  TerraformWorkFlow:
    runs-on: self-hosted

    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.0
        
      - name: HashiCorp - Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3
